server.port=9000
spring.application.name=innovatech-api-gateway

# Rutas del Gateway
spring.cloud.gateway.routes[0].id=bff-route
spring.cloud.gateway.routes[0].uri=http://localhost:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/bff/**

spring.cloud.gateway.routes[1].id=proyectos-route
spring.cloud.gateway.routes[1].uri=http://localhost:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/proyectos/**

spring.cloud.gateway.routes[2].id=recursos-route
spring.cloud.gateway.routes[2].uri=http://localhost:8082
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/recursos/**

# Clave secreta para validar JWT (cambiar en producción)
security.jwt.secret=mi-clave-secreta-muy-larga-para-jwt-mock
