server.port=8083
spring.application.name=innovatech-api-gateway

# Sincronizado con las variables del docker-compose
spring.cloud.gateway.routes[0].id=bff-v2-route
spring.cloud.gateway.routes[0].uri=${BFF_SERVICE_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v2/bff/**

spring.cloud.gateway.routes[1].id=auth-v2-route
spring.cloud.gateway.routes[1].uri=${AUTH_SERVICE_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v2/auth/**

security.jwt.secret=${JWT_SECRET}