server.port=9000
spring.application.name=innovatech-api-gateway

# Rutas del API Gateway hacia los microservicios
spring.cloud.gateway.routes[0].id=bff-v2-route
spring.cloud.gateway.routes[0].uri=${BFF_URL}
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v2/bff/**

spring.cloud.gateway.routes[1].id=auth-v2-route
spring.cloud.gateway.routes[1].uri=${AUTH_URL}
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v2/auth/**

security.jwt.secret=${JWT_SECRET}